spring.application.name=LoadBalancer
spring.threads.virtual.enabled=true
server.port=9000
spring.task.scheduling.pool.size=5

forward.urls=http://localhost:8080,http://localhost:8081,http://localhost:8082